  <?php echo $this->flashSession->output(); 
 
  $username='';
  $password='';
  $rememberMe='';
 
  if($this->cookies->has("username") && $this->cookies->has("password") )
  {
      $username=$this->cookies->get("username");
      $password=$this->cookies->get("password");
      $rememberMe='checked';
  }
?>
<!DOCTYPE html>
<html lang="en">
<head>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="<?php echo $this->url->getBaseUri().'/public/css/ihatethiswork.css' ?>" rel="stylesheet">
</head>

<!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->

</body> 
<body background="b.jpg">
<div class="login">
  <div class="heading">
    <h2>Welcome</h2>
    <form class="form-signin" method="post" action="">

      <div class="form-signin" method="post" action="">
        <span id="reauth-email" class="reauth-email"></span>
        <input "email" name="email" id="inputEmail" class="form-control" placeholder="Enter email" required autofocus value="<?php if(isset($username))echo $username; ?>">
        
          </div>

      
        <span id="reauth-email" class="reauth-email"></span>
          <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required value="<?php if(isset($password))echo $password; ?>">
        </div>
        <div id="remember" class="checkbox">
                    <label>
                    <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>> Remember me
                    </label>
                </div>
               
        
        <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit" >Login</button>
        <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
        <script src="<?php echo $this->url->getBaseUri().'/public/js/ihatethiswork.js' ?>"></script>
       </form>
 		</div>
 </div>

<!-- <form action="" method="post">
  
    <div class="form-group">
      <label>Email address</label>
      <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
    </div>
    <div class="form-group">
      <label>Password</label>
      <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
     
    </div>
    <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>>
 
      <label class="form-check-label" for="rememberMe">Remember me</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
   
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
   
  </form> -->

  
